### ISSUE TITLE
[Race/Feature Request] New line or something when starting races?

### ISSUE THREAD

**Issue by xnaas** [Redjumpman/Jumper-Plugins#106]
**Note: for support questions, please use the [Cog Support Server](https://discord.gg/c6HQUb7)**. This repository's issues are reserved for feature requests and bug reports.

# I'm submitting a ...
- [ ] bug report
- [x] feature request
- [ ] support request => Please do not submit support request here, see note at the top of this template.

# **Cog Information**

Name: race
Version: 1.1.02

# Feature Description
*Please include the motivation / use case for this feature.*

Currently, if you use the compact mode in Discord, racing looks...janky and uneven.

![img](https://xnaas.info/img/acGTT.png)

If a new line was added the the beginning or if the previous `The race is now in progress` message was the start of the message, it would make it look a little better in compact mode.

Here's an example of how NadekoBot does it:

![img](https://xnaas.info/img/Mi9Y8.png)

**Comment by skeith** [comment]
This isn't about new line. Nadeko use embed which is why it's better on display.

**Comment by xnaas** [comment]
That's fine. Still, *something* to push it down a line would be a great improvement. 👍

**Comment by Redjumpman** [comment]
Yukirin is right about the embed being the reason why the output looks better. I think this is a good idea, and I'll add it to my card for V3.

**Comment by xnaas** [comment]
Would be cool, but shot-term, any way to maybe just have a basic line of text or newline added to the beginning? 😄 

I'd submit a PR, but I realized real fast I don't know jack shit about Python yet.

**Comment by Redjumpman** [comment]
When you say "compact mode" do you mean when viewing it on a mobile device?

**Comment by xnaas** [comment]
Mobile doesn't have compact mode, actually.

I'm talking about this setting: ![img](https://xnaas.info/img/81bIw.png)

**Comment by Redjumpman** [comment]
lol yeah see my edit above.

**Comment by xnaas** [comment]
Hah! You're fine. 😄

**Comment by Redjumpman** [comment]
Tricky little fix, because in compact mode the bot always wants to something on the first line. I just ran a test in compact mode, and the update I just pushed for race should stop making it look all jacked up. But I'll keep this issue open, since I'm adding the embed feature for my V3 cogs.

**Comment by xnaas** [comment]
Woohoo, temp fix is great! Thanks a ton! ❤️
