### ISSUE TITLE
[Casino/Bug] Users retain assigned memberships after their memberships is deleted

### ISSUE THREAD

**Issue by jjay12365** [Redjumpman/Jumper-Plugins#108]
**Note: for support questions, please use the [Cog Support Server](https://discord.gg/c6HQUb7)**. This repository's issues are reserved for feature requests and bug reports.

# I'm submitting a ...
- [X] bug report
- [ ] feature request
- [ ] support request => Please do not submit support request here, see note at the top of this template.

# **Cog Information**

Name:  Casino
Version: 2.0.5

# Bug Report
**Screenshot of console: (If Applicable)**
![698b50c67fab04a209496f1311b488be](https://user-images.githubusercontent.com/22643403/36638800-9ae1e38a-19cb-11e8-8077-a562448739bf.png)

**Command used:**
[p]casino resetinstance

**Expected result:**
in settings text file assigned should be false

**Steps to reproduce:**
force assign a membership to a user then delete the membership

**Please tell me about your environment/OS:**

**Comment by jjay12365** [comment]
Also shouldn't using [p]casino resetinstance "all" erase everything like it does when switching modes between local and global?

**Comment by Redjumpman** [comment]
Yeah it should. I'll have to take a look into that as well. I have labeled this critical, since it has a debilitating and demonstrable impact on the way memberships work. I'll do my best to handle this tomorrow.

**Comment by Redjumpman** [comment]
I think I have a fix for this. So far with my changes:
If you revoke a membership, they are set to basic automatically.
If you assign a membership, and then delete it from the list of memberships, it will purge the data
from the user the next time they use a command for a game or stats. 
What was the problem with resetinstance?

This is what it does. When you choose all, it will clear all the global/guild data. This does not include user(global) or member(guild) data. If you want to truly reset everything, you need to use wipe.

Let me know if the above would fix your issue and I'll commit it.

**Comment by jjay12365** [comment]
If you revoke a membership it doesn't need to set them back to automatically. I have a strong feeling my membership updater doesn't work which is why I never switch back to basic even though assign is false. (Separate issue: Discovered after meeting requirements and waiting 10 minutes then force assigning a membership and finding these issues).

assigning a membership then deleting it from the list should work.

thanks for explaining how reset instance works. if you use it to delete memberships either by all or memberships it should, in theory, purge the data from users the next time they use a command for a game or stats. since the membership is deleted that way also.
