### ISSUE TITLE
[V2/Cookie] Cooldown increasing when bot crashes.

### ISSUE THREAD

**Issue by Pundah** [Redjumpman/Jumper-Plugins#109]
**Note: for support questions, please use the [Cog Support Server](https://discord.gg/c6HQUb7)**. This repository's issues are reserved for feature requests and bug reports.

# I'm submitting a ...
- [x ] bug report
- [ ] feature request
- [ ] support request => Please do not submit support request here, see note at the top of this template.

# **Cog Information**

Name:  Cookie
Version: Newest (fresh install)

# Feature Description
*Please include the motivation / use case for this feature.*

# Bug Report
**Screenshot of console: (If Applicable)**
When the bot crashes, The Cookie time starts to count up
**Command used:**
__ any that have to do with the timer__
!steal
!cookie
**Expected result:**
fix?
**Steps to reproduce:**
Bot crash?
**Please tell me about your environment/OS:**
Windows 10 Pc

**Comment by skeith** [comment]
Can you elaborate on `When the bot crashes`.  I need to know the error that causes your bot to crash

**Comment by Redjumpman** [comment]
closing this issue due to lack of response.
