### ISSUE TITLE
[Pokedex/Bug] Pokemon locations shows random and not sorted

### ISSUE THREAD

**Issue by ClaireCruz** [Redjumpman/Jumper-Plugins#119]
**Note: for support questions, please use the [Cog Support Server](https://discord.gg/c6HQUb7)**. This repository's issues are reserved for feature requests and bug reports.

# I'm submitting a ...
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support request here, see note at the top of this template.

# **Cog Information**

Name:  Pokedex
Version: 3.0.04

# Feature Description
*Please include the motivation / use case for this feature.*

# Bug Report
**Screenshot of console: (If Applicable)**

![afbeelding](https://user-images.githubusercontent.com/30986819/41995548-8040b942-7a52-11e8-9afa-3f9502bd95f6.png)

**Command used:**

pokemon location growlithe

**Expected result:**

**Steps to reproduce:**

**Please tell me about your environment/OS:**

**Comment by Redjumpman** [comment]
This bug is fixed.
