### ISSUE TITLE
[V3 Pokedex] Can't find CSVs after changing cog install path

### ISSUE THREAD

**Issue by Tobotimus** [Redjumpman/Jumper-Plugins#124]
# I'm submitting a ...
- bug report

# **Cog Information**

Name:  Pokedex
Version: 3.0.05

# Bug Report
Changing Red's cog install path before installing this cog, and then trying to search for something which involves the CSV files won't work, as the CSV files will be somewhere the cog doesn't expect.

**Command used:**
`[p]pokemon item`/`[p]pokedex`

**Steps to reproduce:**
1. `[p]installpath /path/to/new/install/path`
2. `[p]cog install Jumper-Plugins pokedex`
3. `[p]load pokedex`
4. `[p]pokedex Pikachu`

**Expected result:**
The bot shows the info requested by the command.

**Actual result:**
The bot responds with the message
 *"A Pokémon with that name could not be found."*
And prints the following message to the console:
 *"The csv file could not be found in pokedex data folder."*

**Please tell me about your environment/OS:**
Python 3.6.5
Kubuntu 18.04
Using virtualenv

P.S. PR incoming

**Comment by Redjumpman** [comment]
Fixed in #125
