### ISSUE TITLE
[Shop] Edit 'basic' item info

### ISSUE THREAD

**Issue by Zylvian** [Redjumpman/Jumper-Plugins#129]
**Note: for support questions, please use the [Cog Support Server](https://discord.gg/c6HQUb7)**. This repository's issues are reserved for feature requests and bug reports.

# I'm submitting a ...
- [ ] bug report
- [x] feature request
- [ ] support request => Please do not submit support request here, see note at the top of this template.

# **Cog Information**

Name:  Shop
Version: 3.0.07

# Feature Description
Add a feature that makes it possible to edit the info of a 'basic' item after creation.

# Bug Report
**Screenshot of console: (If Applicable)**

**Command used:**

**Expected result:**

**Steps to reproduce:**

**Please tell me about your environment/OS:**

**Comment by skeith** [comment]
I think #129 #130 #131 #132 can be merged into just one issue

**Comment by Redjumpman** [comment]
Added as of Shop 3.1 #152
