### ISSUE TITLE
[Shop] Fix =shop buy menu width

### ISSUE THREAD

**Issue by Zylvian** [Redjumpman/Jumper-Plugins#133]
**Note: for support questions, please use the [Cog Support Server](https://discord.gg/c6HQUb7)**. This repository's issues are reserved for feature requests and bug reports.

# I'm submitting a ...
- [ ] bug report
- [x] feature request
- [ ] support request => Please do not submit support request here, see note at the top of this template.

# **Cog Information**

Name:  Shop
Version: 3.0.07

# Feature Description
The =shop buy -> shop select menu is too narrow. The 24 character limit makes the info jump to the next line, something that looks really weird. I'm guessing this has something to do with it being a code block inside an embed.

I suggest either making it only an embed or only a code block. Remaking the display method away from code block would also allow emotes in the shop, adding more character to the shops.

# Bug Report
**Screenshot of console: (If Applicable)**

**Command used:**

**Expected result:**

**Steps to reproduce:**

**Please tell me about your environment/OS:**

**Comment by Redjumpman** [comment]
This can't be fixed, because it is a discord window sizing issue. I'll have to explore another way to mess with this... but I'll keep the issue open for now.

**Comment by Redjumpman** [comment]
Added a workaround as of Shop 3.1 #152
