### ISSUE TITLE
Casino in global makes bot crash

### ISSUE THREAD

**Issue by sleepymanakete** [Redjumpman/Jumper-Plugins#137]
# I'm submitting a ...
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support request here, see note at the top of this template.

# **Cog Information**

Name:  Casino
Version:2.1.04

# Bug Report
**Screenshot of console: (If Applicable)**

**Command used:** war

**Expected result:** For the bot to stay online after using casino commands.

**Steps to reproduce:**
1. Toggle global mode
2. Play any games until the bot crashes. 

**Please tell me about your environment/OS:**
Ubuntu 16.4 on a  RPI3.

**Comment by Redjumpman** [comment]
Can anyone else replicate this bug?

**Comment by sleepymanakete** [comment]
Oh! I forgot about this, this problem doesn't seem to happen anymore.
