### ISSUE TITLE
Suggestion for V3 Pokédex

### ISSUE THREAD

**Issue by retke** [Redjumpman/Jumper-Plugins#139]
# I'm submitting a ...
- [ ] bug report
- [x] feature request
- [ ] support request => Please do not submit support request here, see note at the top of this template.

# **Cog Information**

Name: Pokedex
Version: 3.0.06

# Feature Description

The Pokedex works with IDs as you know, from 1 to 806 if my memory's good, and it would be great if we would be able to use the `[p]pokedex` command with the ID *and* the name, so we could do things like this:
```
!pokedex mudkip
!pokedex 258
```
These two commands would show the same data for the mudkip pokemon!

**Comment by Redjumpman** [comment]
Added in 3.0.07
