### ISSUE TITLE
Pokedex pokemon location nonetype object 'find'

### ISSUE THREAD

**Issue by NeoReaper** [Redjumpman/Jumper-Plugins#145]
**Cog**
- Name: Pokedex
- Version: 2.4.02

**Describe the bug**
When using any Pokemon with [p]pokemon location pikachu (for example) I get returned with "'Nonetype' object has no attribute 'find'" (at line 217)

**To Reproduce**
Use [p]pokemon location pikachu

**Expected behavior**
Command to return location of Pokemon.

**Desktop:**
 - OS: Windows 10 Pro
 - Version: Build 17134 (Feature update April 2018)

**Additional context**
All other commands are working as expected.

**Comment by ClaireCruz** [comment]
v2 or v3?

**Comment by NeoReaper** [comment]
The latest version my bot downloaded from the cog which was 2.4.02

**Comment by Redjumpman** [comment]
I'm not longer providing mainstream support to my V2 cogs that have a v3 counter-part released, except for security updates. The current version for V3 is 3.0.07.
