### ISSUE TITLE
[Race/Feature Request] - Allow users to bet on racers 

### ISSUE THREAD

**Issue by Mamalus** [Redjumpman/Jumper-Plugins#86]
# I'm submitting a ...
- [ ] bug report
- [X] feature request
- [ ] support request => Please do not submit support request here, see note at the top of this template.

# **Cog Information**

Name:  Race Cog

# Feature Description
No need to do this, but was wondering to add a feature request to increase the payout increase by percentage when more racer join a race. Have an option to set a percentage or amount increase.

**Comment by Redjumpman** [comment]
I'm not exactly sure yet how I wish to handle payouts. I would like to eventually allow 2nd and 3rd place to get something as well when there are lots of racers. Perhaps a bonus on top of the random prize money per racer could be added. I will have to think on this. Thank you for the suggestion.

**Comment by Mamalus** [comment]
Instead of percentage or amount increased by racers, but allow the users to bet who would win (individual bet). Just like horse betting. I'm just throwing off some ideas

**Comment by skeith** [comment]
If this is implemented, I would like to suggest to @Redjumpman to use mechanism like Harvest Moon Back to Nature horse racing. Each Animal will have random ODD value. The value does contribute to winning percentage but only for a small fraction. The BET will be multiplied with ODD value for the race reward.

**Comment by Mamalus** [comment]
To add more to my statement, this can open to other users to bet the user's animal also without joining the race. [p]race bet @Redjumpman 500. if red joined the race.

**Comment by skeith** [comment]
@Mamalus Yes, I added an update to my previous comment just as you posted yours. However this will make race wait too long since it need to see if there's non player wants to bet.

Maybe make the non player betting as optional command

**Comment by Mamalus** [comment]
@skeith default time is 60 sec (includes joining the race and non-participant  to bet) but I can see your pov if the mod or admin change the cooldown to 15 sec would be hard to bet those users.

**Comment by Redjumpman** [comment]
Done. Try out race V3
