### ISSUE TITLE
[Race/Feature Request] Add purchasable items that affect the outcomes.

### ISSUE THREAD

**Issue by CreatorVilius** [Redjumpman/Jumper-Plugins#92]
# I'm submitting a ...
- [ ] bug report
- [x] feature request
- [ ] support request => Please do not submit support request here, see note at the top of this template.

# **Cog Information**

Name:  Race
Version: 1.1.02

# Better Race Request 
Imo(In my opinion) race should have like a mini shop with buyable buffs, that will make easier to win or harder 😛.
### OR 
Make that there are buffs inside race and when animal hits it, animal will get speed boost, freeze enemy, slowdown enemy or decrease tiles for that animal... Also if buffs would be added you should make coins or something, so, if you hit coin you get +1-10 money...

**Comment by skeith** [comment]
Shop items for race has been thought of as for in race game item, this is not that kind of race yet. This is normal race

**Comment by Redjumpman** [comment]
I think I want to keep race fairly simple and not turn it into a game of looney tunes.
