### ISSUE TITLE
[Casino/Bug] - Exchange command raises an economy error when the user has no account.

### ISSUE THREAD

**Issue by zephyrkul** [Redjumpman/Jumper-Plugins#98]
# I'm submitting a ...
- [X] bug report

# **Cog Information**

Name:  Casino
Version:  1.7.22

# Bug Report
**Screenshot of console: (If Applicable)**
On `casino exchange credits`:
[![Screenshot from Gyazo](https://gyazo.com/a716fc1c86057bb3a3d639035a1de62c/raw)](https://gyazo.com/a716fc1c86057bb3a3d639035a1de62c)

On `casino exchange chips`: 
[![Screenshot from Gyazo](https://gyazo.com/f33b2e7f137c6505fa46fee82d3c9a6a/raw)](https://gyazo.com/f33b2e7f137c6505fa46fee82d3c9a6a)

**Command used:**
`casino exchange`

**Expected result:**
An error message informing the user that they don't have a bank account, and to use `bank register` to create one.

**Steps to reproduce:**
1. User creates a casino account but not a bank account
2. User attempts `casino exchange`

**Please tell me about your environment/OS:**
Doubt that's necessary for this.

Note: I would have created a pull request for this but then I noticed that you use a language feature and I only know English, so any such PR would be incomplete. A simple use of `bank.account_exists(user)` (which returns `True` / `False`) should suffice for the coding half.

**Comment by skeith** [comment]
Redjumpman probably just forgot to add the account check implementation on this cog.

**Comment by Redjumpman** [comment]
I'll take a look at this tonight. Economy in v2 is really annoying when people do not have an account.

**Comment by Redjumpman** [comment]
Took me a while to get to it, but this is now fixed in 1.7.22.
