### ISSUE TITLE
[Pokedex/Feature Request] USUM Pokemon to add to Pokedex

### ISSUE THREAD

**Issue by violetnyte** [Redjumpman/Jumper-Plugins#99]
**Note: for support questions, please use the [Cog Support Server](https://discord.gg/c6HQUb7)**. This repository's issues are reserved for feature requests and bug reports.

# I'm submitting a ...
- [x ] feature request

# **Cog Information**

Name:  pokemon (pokedex)
Version: 2.4.1

# Feature Description
New pokemon in USUM

Poipole
Naganadel
Stakataka
Blacephalon
Zeraora

New pokemon alternate forms in USUM
Dusk Form Lycanroc
Dusk Mane Necrozma
Dawn Wings Necrozma
Ultra Necrozma

Thank you!

**Comment by Redjumpman** [comment]
These have been added in the v3 pokedex rewrite.
